---
- hosts: all
  roles:
    - role: andrewrothstein.anaconda
      anaconda_make_sys_default: True
      anaconda_cleanup: True
      anaconda_pkg_update: False
    - role: '{{playbook_dir}}'
      jupyter_profile_name: jupyter-profile-test
      jupyter_profile_python: 2.7
      jupyter_profile_environment: jupyter-profile-test-environment.yml
