---
- name: create profile
  command: >
    /opt/anaconda/bin/jupyter notebook --generate-config
  args:
    creates: '{{ansible_env.HOME}}/.jupyter/jupyter_notebook_config.py'

- name: set jupyter base_url
  when: jupyter_notebook_base_url is defined
  lineinfile: >-
    state=present
    dest={{ansible_env.HOME}}/.jupyter/jupyter_notebook_config.py
    regexp="^# c.NotebookApp.base_url ="
    line="c.NotebookApp.base_url = '{{jupyter_notebook_base_url}}'"
