---
- name: create {{jupyter_profile_name}} config profile at {{jupyter_profile_install_py}}
  become: yes
  become_user: root
  command: >-
    {{jupyter_profile_env_dir}}/bin/jupyter notebook
    --generate-config --config={{jupyter_profile_install_py}}
  args:
    creates: '{{jupyter_profile_install_py}}'

- name: set jupyter configs
  become: yes
  become_user: root
  with_items: '{{jupyter_profile_config_options | default([])}}'
  lineinfile:
    state: present
    dest: '{{jupyter_profile_install_py}}'
    regexp: '^c.{{item.key}} ='
    line: 'c.{{item.key}} = {{item.value}}'
