---
- name: create jupyter profile dir
  file:
    path: '{{jupyter_config_dir}}'
    state: directory
    mode: 0777

- name: create profile
  command: >
    /opt/anaconda/bin/jupyter notebook --generate-config --config='{{jupyter_config_path}}'
  args:
    creates: '{{jupyter_config_path}}'

- name: set jupyter configs
  with_items: '{{ jupyter_config_options | default([]) }}'
  lineinfile: >-
    state=present
    dest={{jupyter_config_path}}
    regexp="^c.{{ item.key }} ="
    line="c.{{ item.key }} = '{{ item.value }}'"
